# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zhangchi0104"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Twitter"
url = "mailto:alex@otakuma.dev"

[social.params]
icon = "mail"
